// This file is auto-generated by @hey-api/openapi-ts

export type RootData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/';
};

export type RootResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type HealthCheckData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/health';
};

export type HealthCheckResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type ClientOptions = {
    baseUrl: `${string}://${string}` | (string & {});
};